Name:           ros-kinetic-marker-rviz-plugin
Version:        0.0.2
Release:        0%{?dist}
Summary:        ROS marker_rviz_plugin package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/marker_rviz_plugin
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-marker-msgs
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-rviz
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-marker-msgs
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-rviz

%description
The marker_rviz_plugin package contains RViz plugins to visualize messages of
the marker_msgs package using RViz.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Mon Nov 07 2016 Markus Bader <markus.bader@tuwien.ac.at> - 0.0.2-0
- Autogenerated by Bloom

* Fri Sep 30 2016 Markus Macsek <markus.macsek@student.tuwien.ac.at> - 0.0.1-0
- Autogenerated by Bloom

